import React from 'react';
import { BookOpen, Sparkles } from 'lucide-react';
import { NexusNote } from '../../../types';

interface EncyclopediaViewProps {
  node: NexusNote;
  content: string; // The generated encyclopedia text
  onGenerate: () => void;
  isGenerating: boolean;
}

export const EncyclopediaView: React.FC<EncyclopediaViewProps> = ({
  node,
  content,
  onGenerate,
  isGenerating,
}) => {
  if (!content && !isGenerating) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-8 text-center space-y-6">
        <div className="w-20 h-20 bg-nexus-900 rounded-full flex items-center justify-center border border-nexus-800">
          <BookOpen size={40} className="text-nexus-muted opacity-50" />
        </div>
        <div className="max-w-md space-y-2">
          <h3 className="text-xl font-display font-bold text-nexus-text">
            Encyclopedia Entry Missing
          </h3>
          <p className="text-sm text-nexus-muted">
            No formal encyclopedia entry exists for{' '}
            <span className="text-nexus-accent">{node.title}</span>. You can order the Chronicler AI
            to synthesize one from available structured notes.
          </p>
        </div>
        <button
          onClick={onGenerate}
          className="px-6 py-3 bg-nexus-accent text-white font-bold rounded-lg shadow-lg shadow-nexus-accent/20 hover:bg-nexus-accent/90 transition-all flex items-center gap-2"
        >
          <Sparkles size={18} />
          <span>Generate Entry</span>
        </button>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto custom-scrollbar bg-nexus-950">
      <div className="max-w-4xl mx-auto p-12 space-y-8 animate-in fade-in duration-700">
        {/* Encyclopedia Header Style */}
        <div className="border-b-4 border-double border-nexus-800/50 pb-6 text-center">
          <div className="inline-block px-3 py-1 bg-nexus-900 border border-nexus-800 rounded text-[10px] font-black tracking-[0.2em] text-nexus-muted uppercase mb-4">
            Ekrixi Universal Encyclopedia
          </div>
          <h1 className="text-5xl font-display font-black text-nexus-text tracking-tight mb-2">
            {node.title}
          </h1>
          <div className="text-sm font-serif italic text-nexus-muted opacity-70">
            Entry generated by Neural Chronicler — Version 2.0
          </div>
        </div>

        {/* Content Body */}
        <div className="prose prose-invert prose-lg max-w-none font-serif leading-relaxed text-nexus-text/90 first-letter:text-5xl first-letter:font-black first-letter:text-nexus-accent first-letter:mr-3 first-letter:float-left">
          {isGenerating ? (
            <div className="flex flex-col items-center justify-center py-20 space-y-4 animate-pulse">
              <Sparkles size={32} className="text-nexus-accent animate-spin-slow" />
              <span className="text-sm font-mono text-nexus-muted uppercase tracking-widest">
                Synthesizing Knowledge...
              </span>
            </div>
          ) : (
            <div className="whitespace-pre-wrap">{content}</div>
          )}
        </div>

        {/* Footer */}
        {!isGenerating && (
          <div className="pt-12 mt-12 border-t border-nexus-800/30 text-center">
            <button
              onClick={onGenerate}
              className="text-xs text-nexus-muted hover:text-nexus-accent underline decoration-dotted transition-colors"
            >
              Regenerate Entry
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
